### ISSUE TITLE
Proxy samples fail

### ISSUE THREAD

**Issue by baxterhemingway** [packetstream/proxysampler#1]
When trying to test some proxies, which I know are working and have the right credentials from through running in my program. 

I get the following when running the command:
`proxysampler --output json --proxy https://myusername:RanD0mPassWord_country-SomeWhere_session-01@ipaddress:31112 --endpoint https://ifconfig.co/json`

Resulting in:

{"success":0,"fail":1,"average_ttfb":0,"results":[{"proxy":"https://myusername:RanD0mPassWord_country-SomeWhere_session-01@ipaddress:31112","endpoint":"https://ifconfig.co/json","status_code":-1,"latency":{"ttfb":0,"connect":87,"tls_handshake":35086},"error":{"Op":"proxyconnect","Net":"tcp","Source":null,"Addr":null,"Err":{}}}]}

Same goes for using an input file, although proxy is slightly different from input in the result

{
  "success": 0,
  "fail": 1,
  "average_ttfb": 0,
  "results": [
    {
      "proxy": "https://myusername:RanD0mPassWord_country-SomeWhere_session-01@ipaddress:31112",
      "endpoint": "https://ifconfig.co/json",
      "status_code": -1,
      "latency": {
        "ttfb": 0,
        "connect": 88,
        "tls_handshake": 35086
      },
      "error": {
        "Op": "proxyconnect",
        "Net": "tcp",
        "Source": null,
        "Addr": null,
        "Err": {}
      }
    }
  ]
}

**Comment by rdbell** [comment]
Hi, are you testing the PacketStream proxy or a proxy from another provider?

What's the output when you test with curl?

`curl -v -x https://myusername:RanD0mPassWord_country-SomeWhere_session-01@ipaddress:31112`
