### ISSUE TITLE
Redundant tests

### ISSUE THREAD

**Issue by rinogo** [packetstream/proxysampler#2]
When using `--file`, the script seems to skip some proxies while testing other proxies multiple times. In my experimentation, it seems to be the last proxy listed in the file provided that is tested multiple times.

The [fork from @petr-tichy](https://github.com/petr-tichy/proxysampler) doesn't seem to have this problem.

You may wish to incorporate some of his/her changes!

**Comment by rdbell** [comment]
Thanks @rinogo and @petr-tichy

I've imported the changes.
